name: Build and Test Vue Application

on:
  push:
    branches: [main]

jobs:
  build_test_document:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [22.x]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        working-directory: ./my-app
        run: npm ci

      - name: Build application
        working-directory: ./my-app
        run: npm run build --if-present

      - name: Run tests
        working-directory: ./my-app
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./my-app
          build: npm run build
          start: npm run dev
          browser: chrome

      - name: Generate Documentation
        working-directory: ./my-app
        run: npx jsdoc -c jsdoc.config.json

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Prepare artifact directory
        run: |
          mkdir ./content
          cp -r ./my-app/dist/* ./content/
          cp -r ./my-app/docs ./content/docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./content

      - name: build and publish package on NPM
        working-directory: ./my-app
        run: |
          git config --global user.email "youen.valun@gmail.com"
          git config --global user.name "youenv"
          npm run build-npm
          npm version patch
          npm publish
          git add .
          git commit -m "updated version"
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy:
    needs: build_test_document
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
